# Compiling <foo>_test.c with an implementation of <foo>.c of
# of a particular type, we generate a tets for that implementation.

# Implementations via BinarySearchTree: ADTSet
#
UsingBinarySearchTree_ADTSet_test_OBJS = ADTSet_test.o $(MODULES)/UsingBinarySearchTree/ADTSet.o

# Implementations via AVL Tree: ADTSet
#
UsingAVL_ADTSet_test_OBJS = ADTSet_test.o $(MODULES)/UsingAVL/ADTSet.o

# Implementations via B Tree: ADTSet
#
UsingBTree_ADTSet_test_OBJS = ADTSet_test.o $(MODULES)/UsingBTree/ADTSet.o

# The main body of the Makefile
include ../common.mk
